# Generated by Django 4.2.6 on 2024-09-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
