# Generated by Django 4.2.6 on 2024-09-11 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='shop.shop')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='ShopWalletLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions_time', models.DateTimeField(auto_now_add=True)),
                ('transactions_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='shop.shopwallet')),
            ],
            options={
                'verbose_name': 'shop wallet log',
                'verbose_name_plural': 'shop wallet logs',
                'ordering': ['-transactions_time'],
            },
        ),
        migrations.CreateModel(
            name='ShopGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/shop')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.shop')),
            ],
        ),
        migrations.AddIndex(
            model_name='shopwallet',
            index=models.Index(fields=['-amount'], name='shop_shopwa_amount_e6c734_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['-created_at'], name='shop_shop_created_1d4c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['-updated_at'], name='shop_shop_updated_60e54b_idx'),
        ),
    ]
