# Generated by Django 5.1 on 2024-09-04 21:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='shopwallet',
            options={'ordering': ['amount']},
        ),
        migrations.AlterModelOptions(
            name='shopwalletlog',
            options={'ordering': ['-transactions_time'], 'verbose_name': 'shop wallet log', 'verbose_name_plural': 'shop wallet logs'},
        ),
        migrations.RenameField(
            model_name='shopwalletlog',
            old_name='Transactions_time',
            new_name='transactions_time',
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shopgallery',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopwalletlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopwalletlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopwalletlog',
            name='transactions_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopgallery',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['-created_at'], name='shop_shop_created_1d4c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['-updated_at'], name='shop_shop_updated_60e54b_idx'),
        ),
        migrations.AddIndex(
            model_name='shopwallet',
            index=models.Index(fields=['-amount'], name='shop_shopwa_amount_e6c734_idx'),
        ),
    ]
