# Generated by Django 4.2.6 on 2024-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Pending Payment', 'Pending Payment'), ('Rejected', 'Rejected')], max_length=30),
        ),
    ]
