# Generated by Django 4.2.6 on 2024-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
